accounts/urls.py
from accounts.views import register
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', register, name='signup'),
]

expenses/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
]

    # path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    # path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),

receipts/urls.py
from django.urls import path
from receipts.views import (
    AccountCreateView,
    AccountListView,
    ExpenseCategoryCreateView,
    ExpenseCategoryListView,
    ReceiptCreateView,
    ReceiptListView,
    )


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("categories/", ExpenseCategoryListView.as_view(), name="list_categories"),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name="create_category"),
    path("accounts/create/", AccountCreateView.as_view(), name="create_account"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL, related_name="categories", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(USER_MODEL, related_name="account", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(USER_MODEL, related_name="receipts", on_delete=models.CASCADE)
    category = models.ForeignKey("ExpenseCategory", related_name="receipts", on_delete=models.CASCADE)
    account = models.ForeignKey("Account", related_name="receipts", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.vendor

accounts/views.py
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render

# Create your views here.


def register(request):
    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            return redirect('home')
    else:
        f = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': f})

receipts/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import Account, ExpenseCategory, Receipt

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"
    context_object_name = "receipt"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    success_url = "/"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"
    context_object_name = "accounts"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

    
class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense_categories/create.html"
    fields = ["name"]
    success_url = "/"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]
    success_url = "/"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_accounts")

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Account</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <h1>My Expenses</h1>
        <table>
            <thead>
                <th>Name</th>
                <th>Number</th>
                <th>Number of Receipts</th>
            </thead>
            <tbody>
                {% for data in accounts %}
                <tr>
                    <td>{{data.name}}</td>
                    <td>{{data.number}}</td>
                    <td>{{data.receipts.all|length}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
{% endblock content %}

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Recipe - Scrumptious</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
          <li>
            <a href="{% url 'create_receipt' %}">New Receipt</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">Expenses</a>
          </li>
          <li>
            <a href="{% url 'list_accounts' %}">Accounts</a>
          </li>
          <li>
            <a href="{% url 'create_category' %}">New ExpenseCategory</a>
          </li>
          <li>
            <a href="{% url 'create_account' %}">Create Account</a>
          </li>
        {% else %}
        <li>
          <a href="{% url 'login' %}">Login</a>
        </li>
        <li>
          <a href="{% url 'signup' %}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </header>
  {% block content %}
  {% endblock content %}
</body>

</html>

receipts/templates/expense_categories/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Category</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/expense_categories/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <h1>My Expenses</h1>
        <table>
            <thead>
                <th>Name</th>
                <th>Number of Receipts</th>
            </thead>
            <tbody>
                {% for data in expensecategory_list %}
                <tr>
                    <td>{{data.name}}</td>
                    <td>{{data.receipts.all|length}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>Create Receipt</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Due Date</th>
                <th>Category</th>
                <th>Account</th>
            </thead>
            <tbody>
                {% for data in receipt %}
                <tr>
                    <td>{{data.vendor}}</td>
                    <td>{{data.total}}</td>
                    <td>{{data.tax}}</td>
                    <td>{{data.due_date|date:"n, d, y"}}</td>
                    <td>{{data.category}}</td>
                    <td>{{data.account}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
{% endblock content %}